name: event_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  provider: ^6.0.0
  firebase_core: ^3.15.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^5.7.0
  firebase_storage: ^11.6.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.11.1
  intl: ^0.19.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.0

dependency_overrides: 
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true