name: event_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^13.0.0
  provider: ^6.0.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.0
  image_picker: ^1.0.7
  pdf: ^3.10.7
  printing: ^5.11.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
